dist: trusty
language: node_js
cache: yarn
node_js:
- '10'
env:
  global:
  - APPLICATION_NAME="Taskcluster"
  - AUTH0_AUDIENCE="login.taskcluster.net"
  - AUTH0_CLIENT_ID="M9OoQEQVR0M1qtyGvPql3ZDi4T7XMQEA"
  - AUTH0_DOMAIN="auth.mozilla.auth0.com"
  - AUTH0_RESPONSE_TYPE="token id_token"
  - AUTH0_SCOPE="taskcluster-credentials openid profile"
  - OIDC_PROVIDER="mozilla-auth0"
  - SIGN_IN_METHODS="auth0 manual"
  - TASKCLUSTER_ROOT_URL="https://taskcluster.net"
install:
- yarn install --frozen-lockfile
before_install:
- curl -sSfL https://yarnpkg.com/install.sh | bash # Required due to: https://github.com/travis-ci/travis-ci/issues/7951
- export PATH=$HOME/.yarn/bin:$PATH
after_failure:
- yarn build -- --inspect
script:
- yarn lint
- travis_wait yarn build
deploy:
  app: taskcluster-tools
  provider: heroku
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: WTp0wb/G/KfsbBOVsUO+/J0OiVwxKiS+9bmGkrVuEpFDJbEzMFUz1/OqwfZB3DRg4DTdzh/CL7Y9CXbbX9NczykIObzDYpItOWCu8eFF6m1XM8I82GKFy5iY0HTAX3QvlFqyC+nwjT+EFmi90lM9VWtWYn1moZV5On+qBdtwEvw=
