dist: trusty
language: node_js
cache: yarn
node_js:
- '8'
env:
  global:
  - AUTH0_AUDIENCE="login.taskcluster.net"
  - AUTH0_CLIENT_ID="M9OoQEQVR0M1qtyGvPql3ZDi4T7XMQEA"
  - AUTH0_DOMAIN="auth.mozilla.auth0.com"
  - SIGN_IN_METHODS="auth0 manual"
install:
- yarn install --frozen-lockfile
before_install:
- curl -sSfL https://yarnpkg.com/install.sh | bash # Required due to: https://github.com/travis-ci/travis-ci/issues/7951
- export PATH=$HOME/.yarn/bin:$PATH
after_failure:
- yarn build -- --inspect
script:
- yarn lint
- yarn build
deploy:
  app: taskcluster-tools
  provider: heroku
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: BJPt5MRMavaqsH+3IO5E9brWFBhLkfRH1KVjgtUkyOyzi/eQpA0h3fiHu/Kx4lN3pmZVKYDh9Ejk9ppQU3jkzP9K2bbiurLgm6MRNWMSTaEQ3RNuqFefnEFs42wGgdQP7cy1kBoPOBzC65wmgsqdVGP8dw25uc4MtE0xQSL2y1A=
